import React from 'react';
import { Navbar } from '@/components/ui/Navbar';
import { Footer } from '@/components/ui/Footer';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-white">
      <Navbar />
      <main className="pt-32 pb-24 max-w-4xl mx-auto px-4 sm:px-6">
        <div className="prose prose-invert prose-lg max-w-none">
          <h1>Terms of Service</h1>
          <p className="lead">Last updated: March 2026</p>

          <p>By accessing or using OpsFlow, you agree to be bound by these Terms.</p>

          <h3>1. Use of Service</h3>
          <p>
            You may use OpsFlow only for lawful purposes and in accordance with these Terms. You
            agree not to misuse our services or help anyone else do so.
          </p>

          <h3>2. AI Generated Content</h3>
          <p>
            Output generated by our AI agents is probabilistic and may contain errors. You are
            responsible for reviewing and approving AI-generated responses before they are sent to
            your customers.
          </p>

          <h3>3. Termination</h3>
          <p>
            We may suspend or terminate your access to the Service at any time, for any reason,
            without notice.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
